# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/modules/persistence"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/modules/launcher"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/modules/persistence/test"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/modules/launcher/test"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
