# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "/modules/persistence"
      - "/modules/persistence/examples/complete"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-tf):"
    cooldown:
      default-days: 14

  - package-ecosystem: "terraform"
    directories:
      - "/modules/launcher"
      - "/modules/launcher/examples/complete"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-tf):"
    cooldown:
      default-days: 14

  - package-ecosystem: "terraform"
    directories:
      - "/modules/notice-discord"
      - "/modules/notice-discord/examples/complete"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-tf):"
    cooldown:
      default-days: 14

  - package-ecosystem: "terraform"
    directories:
      - "/modules/dns-record"
      - "/modules/dns-record/examples/complete"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-tf):"
    cooldown:
      default-days: 14

  - package-ecosystem: "terraform"
    directories:
      - "/modules/efs-access"
      - "/modules/efs-access/examples/complete"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-tf):"
    cooldown:
      default-days: 14

  - package-ecosystem: "terraform"
    directories:
      - "/modules/notice-github"
      - "/modules/notice-github/examples/complete"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-tf):"
    cooldown:
      default-days: 14

  - package-ecosystem: "terraform"
    directories:
      - "/modules/notice-parameter-store"
      - "/modules/notice-parameter-store/examples/complete"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-tf):"
    cooldown:
      default-days: 14

  - package-ecosystem: "terraform"
    directories:
      - "/modules/service"
      - "/modules/service/examples/complete"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-tf):"
    cooldown:
      default-days: 14

  - package-ecosystem: "gomod"
    directory: "/modules/persistence/test"
    schedule:
      interval: "weekly"
    groups:
      test:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-test):"
    cooldown:
      default-days: 14

  - package-ecosystem: "gomod"
    directory: "/modules/launcher/test"
    schedule:
      interval: "weekly"
    groups:
      test:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-test):"
    cooldown:
      default-days: 14

  - package-ecosystem: "gomod"
    directory: "/modules/notice-discord/test"
    schedule:
      interval: "weekly"
    groups:
      test:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-test):"
    cooldown:
      default-days: 14

  - package-ecosystem: "gomod"
    directory: "/modules/dns-record/test"
    schedule:
      interval: "weekly"
    groups:
      test:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-test):"
    cooldown:
      default-days: 14

  - package-ecosystem: "gomod"
    directory: "/modules/notice-github/test"
    schedule:
      interval: "weekly"
    groups:
      test:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-test):"
    cooldown:
      default-days: 14

  - package-ecosystem: "gomod"
    directory: "/modules/notice-parameter-store/test"
    schedule:
      interval: "weekly"
    groups:
      test:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-test):"
    cooldown:
      default-days: 14

  - package-ecosystem: "gomod"
    directory: "/modules/efs-access/test"
    schedule:
      interval: "weekly"
    groups:
      test:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-test):"
    cooldown:
      default-days: 14

  - package-ecosystem: "gomod"
    directory: "/modules/service/test"
    schedule:
      interval: "weekly"
    groups:
      test:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-test):"
    cooldown:
      default-days: 14

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ (deps-ghaction):"
    cooldown:
      default-days: 14
