version: 0.1
resource_usage:
  aws_route53_record.this:
    monthly_standard_queries: 1314000  # See ../launcher/.infracost-usage.yml for assumption
    monthly_latency_based_queries: 0   # Monthly number of Latency Based Routing queries.
    monthly_geo_queries: 0             # Monthly number of Geo DNS and Geoproximity queries.
